### ISSUE TITLE
Fallo al terminar encuesta y volver a menú

### ISSUE THREAD

**Issue by EdwinPalacio5** [comunidad-ciclo-vii-2019/Proyecto_Investigacion#1]
El funcionamiento de hacer una búsqueda antes de realizar una encuesta  es el esperado, pero al resolver la encuesta y regresar al menú, la búsqueda provoca un error en la aplicación.

![bug](https://user-images.githubusercontent.com/38163898/61011906-a9475b00-a339-11e9-9e20-8647d4692910.jpeg)

**Comment by JPablo1997** [comment]
Quizas sea por los fragments, yo pienso que deberiamos remover esa "funcionalidad".
